# Starting Yale
## 9/26/2026

* *Note 1: What \~\~ back-to-back blog posts?! Surely this means he won't go back to being lazy...*
* *Note 2: fun fact: I write these blogs from pure chain-of-thought without AI, as you could probably tell from how poorly they read ;)* 


This is an update long overdue, but I recently started my PhD studies at Yale University. Upon wrapping up my undergrad at UCLA and saying goodbye to the sweet, sweet dining halls around mid-June, it was a quick turnaround time before I had to report to 87 Trumbull St in New Haven at the end of July for my first day of training. Since then, it's been around two months, so for those curious, I'll share here some of my experiences navigating what it's like to be an incoming student at Yale Economics.

### Classes

As a first year in any economics program, you face the familiar foes: 1) Math Camp, 2) Microeconomics, 3) Macroeconomics, and 4) Econometrics. 

Math camp at Yale lasted three weeks, but was mostly chill in the sense that it was purely supplemental -- there were no exams. Still, math camp is unsatisfactory to basically everyone to say the least; after all, what would you do if you had to condense an entire applied math undergraduate major into fifteen lectures? The first week treated fundamental analysis and linear algebra theory, the second week handled convex optimization, correspondences, and multivariable calculus, and the third week tackled dynamic programming, differential equations, and optimal control. Since I came from undergrad, I still had (to a very small extent) facility with most of these tools, but me and my fellow cohort members already were feeling the heat.

In the academic year, the micro and macro sequences are split into four sessions each; two for each semester. Having already taken the first year PhD micro sequence at UCLA, most of the initial topics in this first quarter (choice theory, demand, risk aversion, etc.) have been pretty familiar, but other topics (such as Afriat's Theorem) were relatively new, so it was nice to still work on problem sets together with my cohort. On the other hand, I was looking at macro with virgin eyes. Still, the initial concepts such as sequential markets equilibrium and steady state, as well as tools like dynamic programming were still fairly neoclassical/"micro-flavored". 

For econometrics, I actually decided to take the second-year sequence, starting with Econometrics III. Econometrics is treated a little differently at Yale, in the sense that you only need to take one course. However, since my interests lie in the field and I was pretty comfortable with probability theory, I was advised to jump straight into rigorous treatment of topics in III to prepare for research. 

PhD level metrics was a big adjustment, especially since the only "formal" training I had in the subject was a program evaluation/reduced-form course I took at UCLA. We jumped straight into identification of nonparametric structural causal models, using control function and nonparametric IV approaches, as well as selection models and measurement error. While I was familiar with what things like instrumental variables or exo/endogeneity were, pinning down how they were being used (for example, is "exogeneity" full independence or a conditional mean restriction? Depends.) took a lot of self-teaching. 

Still, I'm finding the class one of my favorites. Microeconomic theory was the field that first got me into economics, but econometrics is what's keeping me in. I have been super inspired by people like Guido Imbens in their approach to finding intuitive and clean ways to measure and identify causal effects, as well as how much impact good econometrics can have on the field in general (it's furthered my intrigue with applied econometrics/labor research too). I also think the interdisciplinary connection with statistics and computer science is pretty attractive to me: for example, some lines of work in empirical welfare maximization or policy learning take almost an "engineering" approach to econometrics/policymaking, which is exciting.

Altogether, it's been a deluge of learning, but at the same time, very grounding. Even though Yale lets you skip your first-year qualification exams if you do well in the courses, spending hours working through problems and deriving solutions for classwork creates those satisfying clicks and connections in your brain that make you really think, "I got it!" -- at least, more than a ELI5 ChatGPT dopamine hit might do.

### Life as a student

New Haven is quaint and hectic at the same time. You can take a hike up East Rock and soak in the georgeous views of the harbor, or head downtown where there are people revving their motorcycles every night. Yale is very pretty. I've spent a lot of time in the stunning rooms of Sterling Memorial Library, which feature the most intrictate architecture and unique stained glass. It's frankly off-putting -- this kind of style is so different from the bright and trendy vibe at UCLA. Well, I guess it is LA. 

I also realize I took many things at UCLA for granted. The simple things: a Trader Joe's, unlimited dining hall access, going for a swim and hanging out in the campus resort, Century City mall, K-Town, the LA Phil, or even the sauna in John Wooden center. But I miss most my friends at people. The people at UCLA are strivers, doing some of the coolest things, and always looking for a good time. UCLA is by all means a place where people know how to work hard and play hard. The story is a little different in New Haven.

Still, I've found great communities at Yale. I joined the Berkeley College Orchestra, went on a crazy, water-bottle-breaking hike with my fellow cohort, had pizza parties and "soirees" (yes, I too had never heard of what a soiree was before this) with the department, and ate lunch with fellow students while listening to some cool presentations. I don't think it's ever a good idea to think I have to "hermit" myself or go on extended "lock in" arc to succeed; doing things with people is often where I've experienced the most personal growth.


### What do I think about the Economics PhD now?

I thought I knew a lot about what a PhD would entail before I enrolled. Still, I find my opinions shifting in just the span of these couple months. I sometimes think back to when I was stressing about deciding between programs, and thinking the idea of "structural" versus "reduced-form" was a critical differentiator (one can be pedantic even and note when people say "reduced-form", they often refer to the Angrist-Imbens LATE-like frameworks, which are in many ways "structural" nonparametric identification). I was also stressed about fitting into a certain "field-identity" during the visit days, when I wasn't even sure where one field ended and another began. (Honestly, I still don't know. The lines sometimes are blurry. In my opinion, so is the definition of economics a lot of the time.) But still people in economics academia a lot of times are/act confident and "in-the-know". I get really frustrated when I don't really understand something, and even more so when I felt a lot of the time I had to feign like I knew what I was doing to not seem clueless. It led to a lot of questioning and acclimating my conceptions about economics academia.

One thing that hasn't changed though is the belief that doing the PhD would challenge me to grow myself. By all means, nothing kills complacency more for me than thinking, "What happens if you come out of these five to six years with nothing to show for it?" It's still a big investment. Moreso in the backdrop of AI. But think of it this way: no one spent $30 on Minecraft to watch someone build their house for them. They buy it to build and create a world for themselves and play with others. I think the vision of making my own original mark in the field I find deeply fascinating and at the heart of human nature is something I can dedicate at least a PhD's worth to.

