# A Note On AI Conferences
## 9/24/2026

Today is September 24th, 2026, and paper acceptance decisions for the **Fourtieth Annual Conference on Neural Information Processing Systems**, or **NeurIPS**, were just announced. 

NeurIPS 2026 received **30,709** valid submissions for their main conference, of which **7,900** were accepted either as poster, spotlight, or oral presentations, for a total acceptance rate of **25.7%**. For PhD students and faculty in engineering (and related) programs, landing a publication or two at NeurIPS can be a ticket to a prestigious academic job, a frontier research lab, a high-paying quantitative research desk, or just greater recognition (and citations) of your work. In particular, research that has been the backbone of technology like [ChatGPT](https://arxiv.org/abs/1706.03762){target="_blank"} or [generative modeling](https://arxiv.org/abs/1406.2661){target="_blank"} first found a home in NeurIPS. NeurIPS is, of course, not the only conference in the AI/ML space; it together with the International Conference on Machine Learning (ICML) and the International Conference on Learning Representations (ICLR) make up what is known as the "Big Three" of high-impact machine learning research. Other top venues include AAAI, UAI, AISTATS... you get the idea.

With such a massive presence and impact on researcher's careers, technology, and society as a whole, it's no wonder these venues get flooded with tons of submissions. However with AI, these counts have reached unprecedented levels. And people are being tossed and turned as a result of it.

This past cycle, I submitted four papers to NeurIPS along with some of my friends at BruinML and outside collaborators. Here were our results:

* Paper A: 4 (weak accept), 4 (weak accept), 3 (weak reject) -> reject
* Paper B: 4 (weak accept), 3 (weak reject), 3 (weak reject) -> reject
* Paper C: 4 (weak accept), 4 (weak accept), 3 (weak reject) -> **accept**
* Paper D: 4 (weak accept), 4 (weak accept), 5 (accept) -> **reject**

These results seem contradictory at first glance. A paper with an average *accept* rating of 4.33 still got rejected and a paper with an average *reject* rating of 3.67 got accepted, but I would like to interpret why this outcome could be interesting from an "economic" perspective. See, Paper D I had mostly written back in 2024 to 2025, mostly using AI just as a supplemental tool. It is a paper I know the ins and outs of. I would be able to present it at a moment's notice. Most importantly, I think it's core idea was simple, intuitive, and most critcally, written (arguably) rather elegantly and in an easy-to-digest manner, as noted by the reviewing committee themselves. 

Of course, this contrasts with how a large fraction of AI/ML research is being done today, with dense, hard-to-follow, and very technical AI generated slop flooding conferences. However, if one's objective is just to get the paper accepted, my take is that this may have actually been Paper D's *fatal flaw*.

During the reviewing process, I was positive that at least one of our reviewers and the area chair were experts in this particular branch of learning theory. This was evidenced through their specific feedback written in an extremely-convincing human manner (I say this as someone who has seen a lot of AI-generated writing). Because of this, they were able to really pinpoint the exact assumptions and proof weaknesses that a general AI review would probably have glossed over in its context.

During the rebuttal phase, I was able to correct these weaknesses to the best of my ability due to my good understanding of the paper, but ultimately, the area chair was unconvinced. In summary, I believe that *because the reviewers understood the paper and topics so well, they were more confident in their reasons to reject*.

Ok, so what exactly is the issue? Is this not what we seek in science? Each paper should truly be at the frontier of the field, not be lazy with assumptions or problem formulations, and create genuine significant improvements in understanding. 

In this rather noncontroversial view, I am 100% in agreement that this paper should have been rejected.

The problem evidently lies in the *incentives that such systems create*. Papers that are technically dense, incredibly taxing to read, and packed with firework shiny results are less likely to have reviewers who are confident in their assessments, and who can only base their judgements on surface-level results of the paper. What produces such firework-result, polished papers at massive scale? AI. 

The success of this approach, especially in AI conferences, is unparalleled (with me, admittedly, having some personal experience). It is only exacerbated by the fact that if *volunteer* reviewers can't be bothered to expend energy to deeply read or understand an incredibly convoluted, but shiny paper, there is little resistance from them using AI to write a rather uninformative, but generally positive, review themselves. In the language of economics, AI is shifting the scarcity from producing polished research to *certifying* its worth and validity, a phenomenon already being explored in some [recent theoretical frameworks](https://arxiv.org/html/2607.13844v1){target="_blank"}. And in a world where certifying research is incredibly scarce, the paper acceptance process practically becomes nothing short of an arbitrary draw from a lottery. So, if you were a young, opportunistic academic whose value is based largely on publications (as is true in many of these engineering disciplines and industry jobs), why wouldn't you spam twenty AI-generated papers to your favorite conference for about four of them to get accepted too?

Really though, scarce certification has been around long before AI. In the famous [NeurIPS 2014 experiment](https://blog.computationalcomplexity.org/2014/12/the-nips-experiment.html){target="_blank"}, program chairs duplicated submissions and sent them to separate reviewers to evaluate the randomness in the reviewing process. As written in Wikipedia, "Regarding whether the decision in NIPS is completely random or not, John Langford writes: 'Clearly not—a purely random decision would have arbitrariness of ~78%. It is, however, quite notable that 60% is much closer to 78% than 0%.' He concludes that the result of the reviewing process is mostly arbitrary." Certification of good research has always been hard, since it requires so much to align between reviewer and paper: the shared language and notation, familiarity with hybrid literatures, similar schooling/curriculums, understandings of important problems, etc. It is clear that the incredible "synthesis across multiple disciplines" ability of AI makes these factors even harder to align on.

Ok, let me personally back up here because after all, I am doing a PhD in economics (AI/ML research is a carried over interest from my undergrad). Overall though, I think this raises a deeper question, at least for me, on what research should look like. For example, the mathematics community seems very adamant in their stance against the recent OpenAI proof of the Navier-Stokes existence problem, stating that research should aim to *advance human understanding*, for which they argue that OpenAI proof did [not do much of](https://www.npr.org/2026/09/22/nx-s1-5968588/openai-navier-stokes-problem-mathematicians-learn-little){target="_blank"}. It relates back to writing a novel paper in a human-digestible way--such writing and problem formulation is more likely to invite the most effective and informative discussion from a larger pool of experts. I believe that the economics community falls into a similar bucket as the mathematics community in this respect: economists are trained to constantly poke holes and critique others work, cut out fluff, and get straight to the heart of their model, discovered mechanism, or results. Academic economists especially are schooled with an almost uniform curriculum across any program, thus reducing the bandwidth and time needed for people in the field to digest novelties within papers and allocate more bandwidth for digging up substantial flaws. Because of this, I feel there is some "integrity" in the field, well, at least more so than there is in AI conferences. But still, even in economics, the incentives to produce highly polished, but highly convoluted economics papers using AI, especially for junior researchers and PhD students, is quite high, again, due to the scarcity of certification once a paper appears to diverge further from the present "intellectual agenda" or simply becomes too taxing to digest.

Still, it would be foolish to doubt the capabilities of AI. People who were scoffing at the technical capabilities of GPT back in 2022 blinked and saw Millenium Problems being cracked (in time much less than a millenium). Advancing human understanding or not, it's clear they have some level of correct understanding that is perhaps many times just too costly to be internalized by human readers and reviewers. In this case, if research is really about *advancing the field*, what was once viewed as "AI slop" is another instance of AGI/ASI, and humans are simply behind the times. 

My personal take? Writing papers is only half the job; scientific communication is the other half. AI may be ahead of their times, but it's a human researcher's job to distill down their apparent technical prowess into digestible spoonfuls of human understanding, because after all, humans are the ones that want the knowledge. This is a purpose solely driven by human curiosity; whether that knowledge will be used more effectively in the hands of us or our potential AI successors is orthogonal. How many times have you sat in a seminar room, both lethargic and crashing out at the same time because the presenter decided to put fifteen lines of equations and dense notation onto a single slide? So, I hope that while much of one's academic career is based off polished, prestigious, published papers today, the emphasis for evaluating a good researcher or student shifts to how well they are able to expertly distill findings (AI generated or not) to general audiences through talks, seminars, and writing, and establish an agenda of research (AI generated or not) in an interesting and valuable-to-society direction. 






